[project]
name = "deeplearning-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.0",
]
